import Link from 'next/link';
import Header from '@/components/Header';import Footer from '@/components/Footer';import VideoEmbed from '@/components/VideoEmbed';
import {doctor,treatments} from '@/lib/site';import {posts} from '@/lib/blog';

export default function Home(){const post=posts[0];return <><Header/><main>
<section className="hero-new"><div className="shell hero-new-grid"><div className="hero-new-copy"><span className="eyebrow">Cirurgia Vascular · Curitiba</span><h1>Cuidado vascular com ciência, precisão e um olhar <em>individual.</em></h1><p className="lead">Varizes, vasinhos e linfedema tratados com experiência clínica, tecnologia e indicação responsável.</p><div className="hero-actions"><a className="btn primary" href={doctor.whatsappUrl} target="_blank" rel="noreferrer">Agendar avaliação</a><Link className="btn secondary" href="/#tratamentos">Ver tratamentos</Link></div><div className="hero-tags"><span>{doctor.crm}</span><span>{doctor.rqe}</span><Link href="/teleconsulta">Teleconsulta disponível</Link></div></div><div className="hero-portrait-wrap"><div className="hero-portrait-bg"/><img className="hero-portrait" src={doctor.photo} alt="Dra. Claudia Stein Gomes, cirurgiã vascular em Curitiba" fetchPriority="high"/><div className="hero-quote"><span>Flebologia & Linfologia</span><strong>Mais de duas décadas de atuação vascular.</strong></div></div></div></section>
<section className="editorial-strip"><div className="shell"><p>Formação em Cirurgia Vascular pela Santa Casa de Curitiba, aperfeiçoamento em Microcirurgia e Linfologia em Gênova, Itália, mestrado e doutorado pela FEPAR.</p><Link href="/sobre">Conheça a trajetória →</Link></div></section>
<section className="section" id="tratamentos"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Tratamentos</span><h2>O melhor método é o que faz sentido para o seu caso.</h2></div><p>Diagnóstico, ultrassom quando indicado e um plano pensado para cada paciente — sem promessas genéricas.</p></div><div className="treatment-editorial-grid">{treatments.map((t,i)=><Link href={`/tratamentos/${t.slug}`} className={`treatment-editorial ${i===0?'wide':''}`} key={t.slug}><div className="treatment-media"><img src={t.image} alt="" loading="lazy"/></div><div className="treatment-body"><span>{String(i+1).padStart(2,'0')} · {t.kicker}</span><h3>{t.title}</h3><p>{t.summary}</p><b>Saiba mais →</b></div></Link>)}</div></div></section>
<section className="video-story"><div className="shell video-story-grid"><div><span className="eyebrow light">A médica explica</span><h2>Linfedema: informação clara antes de qualquer decisão.</h2><p>Conteúdo em vídeo para entender o quadro, as possibilidades de tratamento e por que o acompanhamento especializado importa.</p><Link className="btn light-btn" href="/tratamentos/linfedema">Entender o linfedema</Link></div><VideoEmbed id="JL9LD-6bRY4" title="Dra. Claudia Stein Gomes explica linfedema"/></div></section>
<section className="section about-new"><div className="shell about-new-grid"><div><span className="eyebrow">Dra. Claudia Stein Gomes</span><h2>Experiência clínica e formação em linfologia que atravessam décadas.</h2></div><div><p>Atuação em flebologia desde 2000 e dedicação ao cuidado do linfedema desde 2002, com abordagem que integra avaliação vascular, fisioterapia especializada e cirurgia linfática em casos selecionados.</p><div className="proof-grid"><div><strong>2000</strong><span>Início da atuação em flebologia</span></div><div><strong>Gênova</strong><span>Microcirurgia e Linfologia</span></div><div><strong>FEPAR</strong><span>Mestrado e Doutorado</span></div></div><Link className="text-link" href="/sobre">Ver formação completa →</Link></div></div></section>
<section className="section blog-preview"><div className="shell"><div className="section-heading"><div><span className="eyebrow">Blog</span><h2>Informação que ajuda você a cuidar melhor da circulação.</h2></div><Link className="text-link" href="/blog">Ver todos os artigos →</Link></div><Link href={`/blog/${post.slug}`} className="featured-post"><div><span className="post-meta">{post.category} · {post.readTime}</span><h3>{post.title}</h3><p>{post.excerpt}</p><b>Ler artigo →</b></div><div className="post-visual"><span>GUIA</span><strong>Compressão<br/>sem confusão.</strong></div></Link></div></section>
<section className="location-section"><div className="shell location-grid"><div><span className="eyebrow light">Gênese Clínica · Mercês</span><h2>Atendimento presencial em Curitiba e opção de teleconsulta.</h2><p>{doctor.address}</p></div><div className="location-actions"><a className="btn light-btn" href={doctor.whatsappUrl} target="_blank" rel="noreferrer">Agendar pelo WhatsApp</a><Link className="btn outline-light" href="/teleconsulta">Conhecer a teleconsulta</Link><a className="text-light" href={doctor.maps} target="_blank" rel="noreferrer">Ver no Google Maps ↗</a></div></div></section>
</main><Footer/></>}
